export const TESTIMONIALS = [
  {
    avatarIcon: 'lucide:hard-hat',
    avatarColor: 'var(--gold)',
    text: 'Trước khi học, tôi nghĩ AI chỉ dành cho IT. Sau khoá học, tôi đã xây được <strong>trợ lý AI cho phòng Sales</strong> — đội ngũ giờ tự xử lý được 80% câu hỏi khách hàng mà không cần tôi can thiệp.',
    quote: 'AI giúp đội Sales tôi xử lý 80% câu hỏi khách hàng tự động.',
    name: 'Nguyễn Minh Tú',
    role: 'Giám đốc Công ty Xây dựng & Nội thất',
  },
  {
    avatarIcon: 'lucide:shopping-bag',
    avatarColor: 'var(--teal)',
    text: 'Tôi đã thử nhiều khoá AI nhưng toàn lý thuyết. Khoá này khác: anh Năng dạy tôi cách <strong>phân rã bài toán kinh doanh</strong> để giao cho AI. Tuần đầu tiên tôi đã tiết kiệm được 12 giờ làm việc.',
    quote: 'Tuần đầu tiên tôi đã tiết kiệm được 12 giờ làm việc nhờ AI.',
    name: 'Trần Thị Lan Anh',
    role: 'Chủ chuỗi thời trang · 5 chi nhánh',
  },
  {
    avatarIcon: 'lucide:stethoscope',
    avatarColor: '#7BAAF5',
    text: 'Phần <strong>Meta-Prompting</strong> là tuyệt nhất — tôi không còn mất hàng giờ viết prompt nữa. Quan trọng hơn là tôi hiểu cách bảo vệ thương hiệu cá nhân khi dùng AI làm content.',
    quote: 'Không còn mất hàng giờ viết prompt — Meta-Prompting thay đổi tất cả.',
    name: 'BS. Lê Quang Vinh',
    role: 'Giám đốc Phòng khám Đa khoa',
  },
  {
    avatarIcon: 'lucide:factory',
    avatarColor: 'var(--gold-l)',
    text: 'Ứng dụng ngay sau khoá: tôi xây được <strong>Giám Đốc HR AI</strong> đọc và chấm điểm CV theo tiêu chí riêng của công ty. Vòng lọc đầu từ 3 ngày xuống còn 2 giờ.',
    quote: 'Vòng lọc CV từ 3 ngày xuống còn 2 giờ nhờ HR AI.',
    name: 'Phạm Duy Khánh',
    role: 'CEO Công ty Sản xuất thực phẩm · 200 NV',
  },
  {
    avatarIcon: 'lucide:plane',
    avatarColor: 'var(--teal)',
    text: 'Là CEO du lịch, tôi đặc biệt ấn tượng với phần <strong>demo live phân tích đối thủ cạnh tranh</strong> trong 5 phút. Anh Năng có kinh nghiệm thực tế nên ví dụ rất sát với ngành của tôi.',
    quote: 'Demo live phân tích đối thủ trong 5 phút — cực kỳ thực tế và sát ngành.',
    name: 'Vũ Thị Hương',
    role: 'Giám đốc Công ty Du lịch & Lữ hành',
  },
  {
    avatarIcon: 'lucide:coins',
    avatarColor: 'var(--green)',
    text: '686K mà tặng kèm 6 AI cá nhân hoá — thực sự đáng giá. Tôi đã áp dụng ngay <strong>Lộ trình 3 bước</strong> và trong tháng đầu đã có 2 quy trình AI chạy ổn định trong công ty.',
    quote: 'Tháng đầu đã có 2 quy trình AI chạy ổn định trong công ty.',
    name: 'Đỗ Ngọc Bình',
    role: 'Giám đốc Công ty Tư vấn Tài chính',
  },
];
